In [3]:
import numpy as np

In [4]:
np.sqrt(17)

4.123105625617661

In [5]:
np.log(4)

1.3862943611198906

In [6]:
np.mean([20, 40, 30, 450, 45, 30])

102.5

In [7]:
np.median([20, 40, 30, 450, 45, 30])

35.0

In [8]:
np.array([2, 3, 4])

array([2, 3, 4])

In [9]:
np.array([[5, 2, 3.5],
    [1, 9, 6]])

array([[5. , 2. , 3.5],
       [1. , 9. , 6. ]])

In [10]:
np.array([[[6, 3],
           [8, 2]],
          [[1,0],
          [0, 1]]    
])

array([[[6, 3],
        [8, 2]],

       [[1, 0],
        [0, 1]]])

In [11]:
np.array([[0, 0, 1],[0, 1]])

array([list([0, 0, 1]), list([0, 1])], dtype=object)

In [12]:
np.array([[5, 8.2],[1, 2]])

array([[5. , 8.2],
       [1. , 2. ]])

In [13]:
np.array([['Ann', 'Kate'],[23, 24]])

array([['Ann', 'Kate'],
       ['23', '24']], dtype='<U4')