In [2]:
import numpy as np

In [5]:
turnout = np.array([0.62, 0.43, 0.79, 0.56])
turnout

array([0.62, 0.43, 0.79, 0.56])

In [7]:
turnout*100

array([62., 43., 79., 56.])

In [8]:
np.array([2, 3, 8]) + np.array([7, 8, 9])

array([ 9, 11, 17])

In [10]:
week1 = np.array([4000, 0, 2000, 0, 1200])
week2 = np.array([1000, 2000, 0, 0, 3500])

In [11]:
week1 + week2

array([5000, 2000, 2000,    0, 4700])

In [12]:
(week1 + week2) / 2

array([2500., 1000., 1000.,    0., 2350.])

In [13]:
[2, 3] ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [14]:
np.array([2, 3]) ** 2

array([4, 9], dtype=int32)