In [2]:
import numpy as np

In [4]:
m = np.array([[2, 5], [6, 8], [1, 3]])
m

array([[2, 5],
       [6, 8],
       [1, 3]])

In [5]:
m.ndim

2

In [6]:
m.shape

(3, 2)

In [7]:
m.size

6

In [9]:
m[1][1]

8

In [10]:
m[1, 1]

8

In [11]:
m[2][3]

IndexError: index 3 is out of bounds for axis 0 with size 2

In [12]:
m[2]

array([1, 3])

In [13]:
m[0:2]

array([[2, 5],
       [6, 8]])

In [14]:
m[1:]

array([[6, 8],
       [1, 3]])

In [15]:
m[:1]

array([[2, 5]])

In [16]:
m[:]

array([[2, 5],
       [6, 8],
       [1, 3]])

In [17]:
m[0:2:2]

array([[2, 5]])

In [19]:
m[0:3:2]

array([[2, 5],
       [1, 3]])

In [20]:
m[::2]

array([[2, 5],
       [1, 3]])

In [21]:
m[::-1]

array([[1, 3],
       [6, 8],
       [2, 5]])