In [1]:
import numpy as np

In [2]:
marks = np.array([5, 4, 3, 5, 4, 3, 4])
marks

array([5, 4, 3, 5, 4, 3, 4])

In [4]:
marks.min()

3

In [6]:
marks.max()

5

In [7]:
marks.mean()

4.0

In [8]:
marks.argmax()

0

In [9]:
marks.argmin()

2

In [10]:
grades = np.array([
    [3, 5, 5, 4, 3],
    [3, 3, 4, 3, 3],
    [5, 5, 5, 4, 3]
])

In [12]:
print(grades)

[[3 5 5 4 3]
 [3 3 4 3 3]
 [5 5 5 4 3]]


In [13]:
grades.mean(axis = 1)

array([4. , 3.2, 4.4])

In [14]:
grades.mean(axis = 0)

array([3.66666667, 4.33333333, 4.66666667, 3.66666667, 3.        ])