In [1]:
import numpy as np

In [2]:
a = 6
b = 9

In [3]:
b > a

True

In [4]:
b >= a

True

In [5]:
b == a

False

In [6]:
ages = np.array([
    [15, 23, 32, 45, 52],
    [68, 34, 55, 78, 20],
    [25, 67, 33, 45, 14]
])

In [9]:
M = ages >= 16

In [10]:
M

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [19]:
work = (ages > 18) & (ages < 60)

In [22]:
work.sum()

10

In [23]:
notwork = (ages < 18) | (ages > 60)

In [24]:
notwork

array([[ True, False, False, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True]])

In [26]:
notwork.sum()

5

In [27]:
ages[ages>=16]

array([23, 32, 45, 52, 68, 34, 55, 78, 20, 25, 67, 33, 45])

In [32]:
ages[(ages >=16) & (ages <60)]

array([23, 32, 45, 52, 34, 55, 20, 25, 33, 45])