In [2]:
import numpy as np

In [4]:
M = np.arange(1, 10, 0.003)
M

array([1.   , 1.003, 1.006, ..., 9.991, 9.994, 9.997])

In [6]:
M.round()

array([ 1.,  1.,  1., ..., 10., 10., 10.])

In [7]:
M.round(1)

array([ 1.,  1.,  1., ..., 10., 10., 10.])

In [8]:
M.round(2)

array([ 1.  ,  1.  ,  1.01, ...,  9.99,  9.99, 10.  ])

In [9]:
A = np.array([2.5, 2.7, 8.1, 9.25])

In [10]:
np.floor(A)

array([2., 2., 8., 9.])

In [11]:
np.ceil(A)

array([ 3.,  3.,  9., 10.])

In [12]:
np.add(A, 2)

array([ 4.5 ,  4.7 , 10.1 , 11.25])

In [13]:
np.subtract(A, 1)

array([1.5 , 1.7 , 7.1 , 8.25])

In [14]:
np.sum(A)

22.55

In [15]:
np.prod(A)

505.74375

In [16]:
d1 = "2019-02-25"
d2 = "2019-02-28"

In [17]:
d1 - d2

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [18]:
np.datetime64(d1)

numpy.datetime64('2019-02-25')

In [19]:
np.datetime64(d2) - np.datetime64(d1)

numpy.timedelta64(3,'D')